name: book_store

description: "A Somali Book Store application with features like cart, wishlist, and categories."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  provider: ^6.1.1
  shimmer: ^2.0.0
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/books/
    - assets/books/images/
    - assets/books/pdfs/
    - assets/books/catalog/
    - assets/books/catalog/somali_literature.json
    - assets/books/catalog/fiction.json
    - assets/books/catalog/search_index.json
    - assets/books/prices.json